name = "Giles R. Greenway"
description = "Data-Larcenist and Carpet-Bagger. Diffident Perpetrator of Generative Noises and Images."
keywords = "python, scraping, sound-sculpture, generative noise"
image = "grg.webp"
theme = "dark"
primary_color = "#00bb00"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://thevahidal.github.io/jake"

[[sections]]
title = "Silly Toys"
description = "Noisy and/or supposedly aesthetic things I've made."
direction = "column"
item_style = "outline"
[[sections.items]]
title = "1dca"
description = "Fun with one-dimensional cellular automata in Numpy and Marimo."
url = "https://augeas.github.io/1dca"
[[sections.items]]
title = "Chaoscillator"
description = "Chaotic attractor sounds with the web audio API, the fourth-order Runge-Kutta methoid in JS, and jQuery."
url = "https://augeas.github.io/Chaoscillator/"
[[sections.items]]
title = "Lyapunov Fractals"
description = "Looping, morphing lyapunov fractals, optionally in your browser via WASM, done in Marimo with numpy."
url = "https://augeas.github.io/lyapunov/"
[[sections]]
title = "Hacker Camp Noises"
description = "Sometimes I make and explain noises at hacker camps."
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/8LaoaS3PIfM"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/HPNavwYEwDo"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/Z5ZvWunP46s"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/b03P4eaeUzE"
[[sections]]
title = "Grand Theft Data"
description = "Web scraping for fun and profit, or occasional retribution."
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Scrapers at apify.com"
description = "In which I pedal my music streaming analytics wares."
url = "https://apify.com/augeas"
[[sections]]
title = "Other Links"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/gilesgreenway/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/mastodon"
title = "Mastodon"
url = "https://eleusis.social/@augeas"
[[sections.items]]
icon = "https://cdn.simpleicons.org/soundcloud"
title = "Soundcloud"
url = "https://soundcloud.com/giles-richard-greenway"
