name = "Giles R. Greenway"
description = "Data-Larcenist and Carpet-Bagger. Diffident Perpetrator of Generative Noises and Images."
keywords = "python, scraping, sound-sculpture, generative noise"
image = "jake.webp"
theme = "dark"
primary_color = "#0000ff"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://thevahidal.github.io/jake"

[[sections]]
title = "Hacker Camp Noises"
description = "Sometimes I make and explain noises as hacker camps"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://app.media.ccc.de/v/SHA2017-220-in_discrete_music"
description = "The time I headline SHA2017 by mistake."
[[sections.items]]
title = "Nightcrawler"
description = "A mesmerizing thriller delving into the dark world of crime journalism"
url = "https://www.imdb.com/title/tt2872718/"
[[sections.items]]
title = "Brokeback Mountain"
description = "A groundbreaking romantic drama challenging societal expectations"
url = "https://www.imdb.com/title/tt0388795/"
[[sections.items]]
title = "Prisoners"
description = "A gripping thriller entangling a detective in a web of secrets during a kidnapping investigation"
url = "https://www.imdb.com/title/tt1392214/"


[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/jakegyllenhaal"
[[sections.items]]
icon = "https://cdn.simpleicons.org/imdb/ffffff"
title = "IMDb"
url = "https://www.imdb.com/name/nm0350453/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/wikipedia/ffffff"
title = "Wikipedia"
url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
[[sections.items]]
title = "Rotten Tomatoes"
icon = "https://cdn.simpleicons.org/rottentomatoes/ffffff"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
