name = "Giles R. Greenway"
description = "Data-Larcenist and Carpet-Bagger. Diffident Perpetrator of Generative Noises and Images."
keywords = "python, scraping, sound-sculpture, generative noise"
image = "grg.webp"
theme = "dark"
primary_color = "#00bb00"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://thevahidal.github.io/jake"

[[sections]]
title = "Silly Toys"
description = "Noisy and/or supposedly aesthetic things I've made."
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Chaoscillator"
description = "Chaotic attractor sounds with the web audio API, the fourth-order Runge-Kutta methoid in JS, and jQuery."
url = "https://augeas.github.io/Chaoscillator/"
[[sections.items]]
title = "lyapunov Fractals"
description = "Looping, morphing lyapunov fractals, optionally in your browser via WASM, done in Marimo with numpy."
url = "https://augeas.github.io/lyapunov/"
[[sections]]
title = "Hacker Camp Noises"
description = "Sometimes I make and explain noises at hacker camps."
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/8LaoaS3PIfM"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/HPNavwYEwDo"

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/jakegyllenhaal"
[[sections.items]]
icon = "https://cdn.simpleicons.org/imdb/ffffff"
title = "IMDb"
url = "https://www.imdb.com/name/nm0350453/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/wikipedia/ffffff"
title = "Wikipedia"
url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
[[sections.items]]
title = "Rotten Tomatoes"
icon = "https://cdn.simpleicons.org/rottentomatoes/ffffff"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
